name: Flutter App Distribution

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.27.3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase CLI
        run: firebase login:ci --token "${{ secrets.FIREBASE_AUTH_TOKEN }}"

      - name: Install dependencies
        run: flutter pub get

      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Build APK
        run: flutter build apk --release

      - name: Deploy to Firebase App Distribution
        run:
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
          --app quomia_${{ env.version }}
        env:
          FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
